### ISSUE TITLE
File parsing fails with "Sequence has more than one element" exception

### ISSUE THREAD

**Issue by TheRealDougSchmidt** [AquaticInformatics/eHSN-field-data-plugin#28]
This measurement file fails to parse with a nasty internal stack trace.

```
2019-06-18 12:01:48,086 [1] INFO  PluginTester.Tester - Loading data file '..\data\01EE005_20190612_FV.xml'
2019-06-18 12:01:48,088 [1] INFO  EhsnPlugin - Parsing eHSN 'v1.3.2' from location '01EE005' (MOOSE PIT BROOK AT TUPPER LAKE) collected on 2019/06/12
2019-06-18 12:01:48,089 [1] INFO  EhsnPlugin - Successfully parsed one visit '2019-06-12T12:51:00.0000000-08:00/2019-06-12T13:59:00.0000000-08:00' for location '01EE005'
2019-06-18 12:01:48,089 [1] ERROR EhsnPlugin - Can't change the LevelSurvey.OriginReferencePointName from 'NS86-027' to 'NS16-041'. Retaining first origin.
2019-06-18 12:01:48,103 [1] ERROR EhsnPlugin - File can be parsed but an error occurred: Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at EhsnPlugin.Mappers.LevelSurveyMapper.Map(EHSN eHsn) in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Mappers\LevelSurveyMapper.cs:line 93
   at EhsnPlugin.Mappers.FieldVisitMapper.MapLevelSurveys() in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Mappers\FieldVisitMapper.cs:line 202
   at EhsnPlugin.Parser.AppendMappedMeasurements(FieldVisitMapper mapper, FieldVisitInfo fieldVisitInfo) in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Parser.cs:line 121
   at EhsnPlugin.Parser.Parse(EHSN eHsn) in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Parser.cs:line 88
   at EhsnPlugin.Plugin.ParseFile(Stream fileStream, IFieldDataResultsAppender fieldDataResultsAppender, ILog logger) in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Plugin.cs:line 23
```

[01EE005_20190612_FV.xml.txt](https://github.com/AquaticInformatics/eHSN-field-data-plugin/files/3303131/01EE005_20190612_FV.xml.txt)

**Comment by TheRealDougSchmidt** [comment]
Fixed by #29 in [v18.4.30](https://github.com/AquaticInformatics/eHSN-field-data-plugin/releases/tag/v18.4.30)
