### ISSUE TITLE
Single reading files can't be parsed

### ISSUE THREAD

**Issue by TheRealDougSchmidt** [AquaticInformatics/eHSN-field-data-plugin#40]
A file with just a single StageMeas row cannot be parsed.

https://github.com/AquaticInformatics/eHSN-field-data-plugin/blob/master/src/EhsnPlugin/Mappers/FieldVisitMapper.cs#L61

That `if (allTimes.Count() < 2)` condition should be `if (!allTimes.Any())` so that it works with a single-reading file.

```
14:35:00.324 ERROR - File can be parsed but an error occurred: Can't infer the start and end time. Too few time values found in the file. Date=2020/01/13 Count=1 Times=2020-01-13T14:15:00.0000000-08:00
   at EhsnPlugin.Mappers.FieldVisitMapper.GetVisitTimePeriod() in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Mappers\FieldVisitMapper.cs:line 64
   at EhsnPlugin.Mappers.FieldVisitMapper.MapFieldVisitDetails() in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Mappers\FieldVisitMapper.cs:line 37
   at EhsnPlugin.Parser.AppendMappedFieldVisitInfo(FieldVisitMapper mapper, LocationInfo locationInfo) in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Parser.cs:line 105
   at EhsnPlugin.Parser.Parse(EHSN eHsn) in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Parser.cs:line 98
   at EhsnPlugin.Plugin.ParseFile(Stream fileStream, IFieldDataResultsAppender fieldDataResultsAppender, ILog logger) in C:\git\eHSN-field-data-plugin\src\EhsnPlugin\Plugin.cs:line 23
14:35:00.326 INFO  - Saving 0 visits data to '../results\05ND012_20200113_FV.xml.json'
```

**Comment by TheRealDougSchmidt** [comment]
Fixed by #41 in [v19.2.5](https://github.com/AquaticInformatics/eHSN-field-data-plugin/releases/tag/v19.2.5)
